analogdevicesinc/HighSpeedConverterToolbox

+adi/+QuadMxFE/Rx.m
+adi/+QuadMxFE/Tx.m

Move HMC425 control from TX to RX for QMxFE

---

+adi/+QuadMxFE/Rx.m
+adi/+QuadMxFE/Tx.m

Signed-off-by: Travis Collins <travis.collins@analog.com>

Remove en controls from Rx since they do not exist in the driver anymore

---

+adi/+QuadMxFE/Base.m
+adi/+QuadMxFE/Rx.m
+adi/+QuadMxFE/Tx.m

Add API updates for current QuadMxFE Configuration

Mxfe updates

---

+adi/+sim/+AD9081/Rx.m
+adi/+sim/+AD9081/Tx.m
+adi/+sim/+common/ADC9081.m
+adi/+sim/+common/ADCGeneric.m
+adi/+sim/+common/DAC9081.m
+adi/+sim/+common/DACGeneric.m

Update MxFE simulation models to enable variable samplerate

---

+adi/+AD9081/Tx.m
+adi/+QuadMxFE/Tx.m

Fix typo in set parameters for NCO gains of (Q)MxFE APIs.

MxFE and QMxFE gain setting fix

---

+adi/+QuadMxFE/Tx.m

Add bypasses to debug attribute writes

---

hsx_examples/ad9081/ad9081PFIR.m
hsx_examples/mxfe_sim/CreateFilterFile.m

Signed-off-by: Srikanth Pagadarai <srikanth.pagadarai@analog.com>

Fixed a couple of namespace references.

---

+adi/+QuadMxFE/Tx.m
+adi/CalBoardVCU118.m
hsx_examples/qmxfe/QuadMxFE_MCS.m
hsx_examples/qmxfe/QuadMxFE_SimpleTxRx.m
hsx_examples/qmxfe/QuadMxFE_SystemAlignmentFIR.m

PR moves DAC current API into TX class and updates demos to use this. Specific class for Calibration board was added as well.

QMxFE demo and interface updates

---

+adi/+sim/+AD9081/Base.m
+adi/+sim/+common/CDDC.m
+adi/+sim/+common/CDUC.m
+adi/+sim/+common/FDDC.m
+adi/+sim/+common/FDUC.m
hsx_examples/mxfe_sim/mxfe_view_responses.m

Add methods to AD9081 model to export filter responses

---

hsx_examples/qmxfe/QuadMxFE_MCS.m
hsx_examples/qmxfe/QuadMxFE_SimpleTxRx.m
hsx_examples/qmxfe/QuadMxFE_SystemAlignmentFIR.m

PR adds QMxFE example for MCS and updates so APIs around DAC current settings.

Add QMxFE examples

---

+adi/+QuadMxFE/Rx.m
hsx_examples/qmxfe/CalBoardVCU118.m
hsx_examples/qmxfe/QuadMxFE_MCS.m

Update demos for QMxFE

---

hsx_examples/qmxfe/QuadMxFE_ADCtoDAC_Loopback.m

Add QMxFE Loopback example

---

+adi/Contents.m
+adi/Version.m
Jenkinsfile
README.md
test/DemoTests.m

Signed-off-by: Srikanth Pagadarai <srikanth.pagadarai@analog.com>

Version: Bump to v20.2.1

---

hsx_examples/qmxfe/QuadMxFE_MCS_revC.m

Add QMxFE example for Rev C

---

+adi/+AD9083/Base.m
+adi/+AD9083/Rx.m

Add AD9083 support

---

hsx_examples/qmxfe/QuadMxFE_MCS.m
hsx_examples/qmxfe/QuadMxFE_SimpleTxRx.m
hsx_examples/qmxfe/QuadMxFE_SystemAlignmentFIR.m

Changed all the main example scripts to support Rev C operation.

Updated all examples for Rev C

---

hsx_examples/qmxfe/QuadMxFE_ADCtoDAC_Loopback.m
hsx_examples/qmxfe/QuadMxFE_MCS.m
hsx_examples/qmxfe/QuadMxFE_SimpleTxRx.m

Looking to get the scripts updated to latest version for the last release of the 2020a toolbox. Thanks!

Updated scripts!

---

JenkinsfileHW

Signed-off-by: Julia Pineda <Julia.Pineda@analog.com>

use MATLAB R2021b

---

JenkinsfileHW

Signed-off-by: Julia Pineda <Julia.Pineda@analog.com>

Test Harness Updates: Define required agents

---

JenkinsfileCron

Add separate Jenkinsfile for synthesis

---

docs/_templates/sysobj.html

Add updates sysobj template

---

JenkinsfileHW

Signed-off-by: Julia Pineda <Julia.Pineda@analog.com>

Use netbox as nebula-config source

---

CI/gen_doc/docs/_pages/index.md

Signed-off-by: Pagadarai <Srikanth.Pagadarai@analog.com>

Updated doc overview page

---

CI/gen_doc/docs/_pages/models.md

Fix link to behavior model for AD9081

---

CI/gen_doc/docs/_pages/ad9081.md
CI/gen_doc/docs/_templates/mkdocs.tmpl

Signed-off-by: Travis Collins <Travis.Collins@analog.com>

Add doc specific page for AD9081

---

JenkinsfileHW
test/runHWTests.m

Signed-off-by: Julia Pineda <Julia.Pineda@analog.com>

Add AD9081, DAQ3 to hw test pipeline

---

hsx_examples/ad9081/ad9081_rxtx_loopback.m

Add basic MxFE example

---

CI/scripts/read_ports_json.py

Signed-off-by:Ionut Muthi <Ionut.Muthi@analog.com>

update read_ports_json script

---

.github/workflows/doc.yml

Change GHA to py 3.7

---

test/BSPTestsBase.m

Signed-off-by: Pagadarai <Srikanth.Pagadarai@analog.com>

Updated BSPTestsBase to collect timing summary log

---

+adi/+AD9164/Base.m
+adi/+AD9164/Tx.m
+adi/+AD916x/Base.m
+adi/+AD916x/Tx.m

add support for AD916x devices 
updated AD9162

add AD916x , AD9164

---

CI/ci_flags.md
Jenkinsfile

CI: skip=HDL Tests;skip=NonHW Tests;skip=Hardware Streaming Tests

Enable commit flag parsing support

---

CI/gen_doc/docs/_pages/install.md

CI: skip=HDL Tests;skip=NonHW Tests;skip=Hardware Streaming Tests

Replaced TRx with HSX in install doc page

---

+adi/+AD9081/Rx.m

Add check for powerdown mode in AD9081

[AD9081] Make sure datapath is in powered up state

---

JenkinsfileHW

udev is required for SD muxed board when using nebula dev branch

Add udev in resources

---

+adi/+AD9081/Tx.m

Add skipinit control to all classes with special case for MxFE

Add skip init features needed for stingray testing
